### PR TITLE
Fix davix-get towards databridge/S3. Fix SEGV on error

### PR DESCRIPTION
**Pull request by ffurano**

### CODE REVIEW

**Comment by adevress** [comment]
Thx fab,

I will have a look this evening :)

**Comment by adevress** [comment]
Could you have a loçok to the identation Fab ?

It seems that your patch has an ident of 2, the project has an indent of 4.

It's good for me but It would screw up the alignment if I merge it like it is.

**Comment by ffurano** [comment]
Not bad to loose 24 hours for an urgent fix just to comply with silly git netiquette. The indentation can also be fixed after the testing :-|

**Comment by adevress** [comment]
You did not say me it's urgent ><
wtv

**Comment by ffurano** [comment]
:-(
Anyway it works now, which is what we wanted :-D
Thank you for being available. BTW I need to talk to you again.

**Pull request merged**
